name: Run The Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd ciphers_project
          python3 manage.py test
      - name: Build and push the image
        run: |
          docker login --username Neha-Reddy-08 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/neha-reddy-08/cipher-service:latest --file Dockerfile .
          docker push ghcr.io/neha-reddy-08/cipher-service:latest
